import "./globals.css";
import { Space_Grotesk } from "next/font/google";
import { Familjen_Grotesk } from "next/font/google";

const space = Space_Grotesk({
  subsets: ["latin"],
  display: "swap",
});

const familjen = Familjen_Grotesk({
  subsets: ["latin"],
  variable: "--familjen-font",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className={familjen.variable} lang="en">
      <body>{children}</body>
    </html>
  );
}
